baseURL = ""
languageCode = "en-us"
title = "Hugo Blog"
paginate = 6
canonifyURLs = true

[markup.goldmark.renderer]
unsafe = true

[permalinks]
categories = "/blog/categories/:slug"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

sectionPagesMenu = "main"



